//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTBusService.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ZTTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ZTTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZTBusService.App_GlobalResources.ZTTranslations", typeof(ZTTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string countryCode {
            get {
                return ResourceManager.GetString("countryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New {0}.
        /// </summary>
        public static string CreateNewX {
            get {
                return ResourceManager.GetString("CreateNewX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a date..
        /// </summary>
        public static string DataTypeDateTime {
            get {
                return ResourceManager.GetString("DataTypeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Hired.
        /// </summary>
        public static string dateHired {
            get {
                return ResourceManager.GetString("dateHired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to driver.
        /// </summary>
        public static string driverLowerCase {
            get {
                return ResourceManager.GetString("driverLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on validating {0} : .
        /// </summary>
        public static string ErrorOnValidatingX {
            get {
                return ResourceManager.GetString("ErrorOnValidatingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exception trying to add new {0}:.
        /// </summary>
        public static string exceptionTryingToAddX {
            get {
                return ResourceManager.GetString("exceptionTryingToAddX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field &apos;{0}&apos; must be a date.
        /// </summary>
        public static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field &apos;{0}&apos; must be a number.
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Name.
        /// </summary>
        public static string fullNameDriver {
            get {
                return ResourceManager.GetString("fullNameDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string homePhone {
            get {
                return ResourceManager.GetString("homePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Id.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  New {0} record added. .
        /// </summary>
        public static string NewXRecordAdded {
            get {
                return ResourceManager.GetString("NewXRecordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Pattern.
        /// </summary>
        public static string phonePattern {
            get {
                return ResourceManager.GetString("phonePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Please select ---.
        /// </summary>
        public static string pleaseSelect {
            get {
                return ResourceManager.GetString("pleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string postalCode {
            get {
                return ResourceManager.GetString("postalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Pattern.
        /// </summary>
        public static string postalPattern {
            get {
                return ResourceManager.GetString("postalPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid value for &apos;{1}&apos;.
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a value is required for &apos;{0}&apos;.
        /// </summary>
        public static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Code.
        /// </summary>
        public static string provinceCode {
            get {
                return ResourceManager.GetString("provinceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Label.
        /// </summary>
        public static string provinceStateLabel {
            get {
                return ResourceManager.GetString("provinceStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty or just spaces.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to List.
        /// </summary>
        public static string ReturnToList {
            get {
                return ResourceManager.GetString("ReturnToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string streetAddress {
            get {
                return ResourceManager.GetString("streetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of {0} should be from 2 to 50..
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driver (id: {0}, full name: {1}) has been deleted. .
        /// </summary>
        public static string TempMessageDeleteSuccessIdName {
            get {
                return ResourceManager.GetString("TempMessageDeleteSuccessIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete the driver (id: {0}, full name: {1}) : .
        /// </summary>
        public static string TempMessageErrorOnDeleteIdName {
            get {
                return ResourceManager.GetString("TempMessageErrorOnDeleteIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update information for the driver (id: {0}, full name: {1}) : .
        /// </summary>
        public static string TempMessageErrorOnEditIdName {
            get {
                return ResourceManager.GetString("TempMessageErrorOnEditIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information for this driver (id: {0}, full name: {1}) has been updated..
        /// </summary>
        public static string TempMessageUpdateSuccessIdName {
            get {
                return ResourceManager.GetString("TempMessageUpdateSuccessIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} is {1}. .
        /// </summary>
        public static string TempMessageXisX {
            get {
                return ResourceManager.GetString("TempMessageXisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New {0}.
        /// </summary>
        public static string titleAddNewX {
            get {
                return ResourceManager.GetString("titleAddNewX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Phone.
        /// </summary>
        public static string workPhone {
            get {
                return ResourceManager.GetString("workPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Code is not a valid Canadian province code..
        /// </summary>
        public static string WrongProvincePattern {
            get {
                return ResourceManager.GetString("WrongProvincePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be just blanks/spaces..
        /// </summary>
        public static string XCannotBeBlanks {
            get {
                return ResourceManager.GetString("XCannotBeBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be derived from {1} or {2}.
        /// </summary>
        public static string XcannotBeDerivedFromXorX {
            get {
                return ResourceManager.GetString("XcannotBeDerivedFromXorX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be in the future..
        /// </summary>
        public static string XCannotBeFuture {
            get {
                return ResourceManager.GetString("XCannotBeFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should only contain English alphabet letters and be only 2 letters long..
        /// </summary>
        public static string XCanOnlyBe2EnglishLetters {
            get {
                return ResourceManager.GetString("XCanOnlyBe2EnglishLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid date formate : 2005-12-31.
        /// </summary>
        public static string XIsInvalidDate {
            get {
                return ResourceManager.GetString("XIsInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid phone number. Please format like 222-222-2222..
        /// </summary>
        public static string XIsInvalidPhoneNumber {
            get {
                return ResourceManager.GetString("XIsInvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid Canadian postal pattern: A3A 3A3.
        /// </summary>
        public static string XIsInvalidPostal {
            get {
                return ResourceManager.GetString("XIsInvalidPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; is not on file.
        /// </summary>
        public static string XisNotOnFile {
            get {
                return ResourceManager.GetString("XisNotOnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} record created.
        /// </summary>
        public static string XRecordCreated {
            get {
                return ResourceManager.GetString("XRecordCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zhenzhen&apos;s Bus Service.
        /// </summary>
        public static string ZhenzhenBusService {
            get {
                return ResourceManager.GetString("ZhenzhenBusService", resourceCulture);
            }
        }
    }
}
