//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTBusService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trip()
        {
            this.tripStops = new HashSet<tripStop>();
        }

        [ScaffoldColumn(false)]
        public int tripId { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name = "Start Time")]
        public int routeScheduleId { get; set; }

        public System.DateTime tripDate { get; set; }

        [ScaffoldColumn(false)]
        public int driverId { get; set; }

        [ScaffoldColumn(false)]
        public int busId { get; set; }

        [DataType(DataType.MultilineText)]
        public string comments { get; set; }

        public virtual bus bus { get; set; }
        public virtual driver driver { get; set; }
        public virtual routeSchedule routeSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tripStop> tripStops { get; set; }
    }
}
